routes/web.php
<?php

Auth::routes();

Route::group(['middleware' =>['auth']],function(){
    Route::get('/', 'DashboardController@index')->name('dashboard');
    Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');
    
    Route::group(['middleware' => ['gudang']], function() {
        Route::get('penerimaan', 'PembelianController@penerimaan')->name('penerimaan.index');
        Route::get('penerimaan/{pembelian}', 'PembelianController@show')->name('penerimaan.show');
        Route::get('penerimaan/{pembelian}/terima', 'PembelianController@terima')->name('penerimaan.terima');
    });

    Route::group(['middleware' => ['admin']], function() {
        // User
        Route::resource('user', 'UserController');
        // Barang
        Route::get('barang/{barang}/delete', 'BarangController@destroy')->name('barang.delete');
        Route::resource('barang', 'BarangController');
        // Supplier
        Route::get('supplier/{supplier}/delete', 'SupplierController@destroy')->name('supplier.delete');
        Route::resource('supplier', 'SupplierController');
        // Pembelian Barang
        Route::get('pembelian/tambah-barang', 'PembelianController@tambahBarang')->name('pembelian.tambah-barang');
        Route::get('pembelian/{pembelian}/delete', 'PembelianController@destroy')->name('pembelian.delete');
        Route::resource('pembelian', 'PembelianController');
    });

    Route::group(['middleware' => ['kasir']], function() {
        Route::resource('stock-barang', 'StockBarangController');
        Route::get('penjualan-barang/tambah-barang', 'PenjualanBarangController@tambahBarang')->name('penjualan-barang.tambah-barang');
        Route::resource('penjualan-barang', 'PenjualanBarangController');
    });
});

resources/views/user-mgmt/_user.blade.php
<div class="card">
    <div class="card-body">
        <div class="form-group">
            {!! Form::hidden('id', null) !!}
            {!! Form::label('name', 'Name:') !!}
            {!! Form::text('name', null, ['class' => 'form-control']) !!}
        </div>
        <div class="form-group">
            {!! Form::label('email', 'Email:') !!}
            {!! Form::email('email', null, ['class' => 'form-control']) !!}
        </div>
        <div class="form-group">
            {!! Form::label('password', 'Password:') !!}
            {!! Form::input('password', 'password', null, ['class' => 'form-control']) !!}
        </div>
        <div class="form-group">
            {!! Form::label('role', 'Role:') !!}
            {!! Form::select('role_id', $roles, null, ['placeholder' => 'Pick a role...', 'class' => 'form-control']) !!}
        </div>
        <div class="form-group">
            {!! Form::submit($submitLabel, ['class' => 'btn btn-info pull-righ']) !!}
            <a onclick="window.history.back()" type="button" class="btn btn-info pull-righ" >Cancel</a>
        </div>
    </div>
</div>

resources/views/user-mgmt/base.blade.php
@extends('layouts.app-base')
@section('content')
  
    @yield('action-content')
  
@endsection

resources/views/user-mgmt/create.blade.php
@extends('user-mgmt.base')
@section('action-content')

<div class="container">
<div class="row">
<div class="col-md-10">
<section class="panel panel-primary">
    <div class="panel-heading">Tambah User Baru</div>
    <div class="panel-body">
 
    {!! Form::open(['route' => 'user.store']) !!}

        @include('user-mgmt._user', ['roles' => $roles, 'submitLabel' => 'Save'])

    {!! Form::close() !!}
    </div>
</section>
</div>
</div>
</div>
@stop

resources/views/user-mgmt/crt.blade.php
@extends('user-mgmt.base')
@section('action-content')
    <!-- Main content -->
    <section>
    <div class="panel panel-default">
    <div class="panel-heading">User</div>
    <div class="panel-body">

       
        <table id="userDtab" class="table table-xs table-striped table-bordered" style="width:100%">
            <thead>
                <tr>
                    <th></th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Role</th>
                </tr>
            </thead>
            <tbody>
               
                    <tr>
                       
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td colspan="5" class="text-center text-muted">Tidak ada data</td>
                        <td style="display: none;"></td>
                        <td style="display: none;"></td>
                        <td style="display: none;"></td>
                        <td style="display: none;"></td>
                    </tr>
        
            </tbody>
        </table>

    </div>
</div>

</section>

@endsection

resources/views/user-mgmt/edit.blade.php
@extends('user-mgmt.base')
@section('action-content')

<div class="panel panel-primary">
    <div class="panel-heading">Edit User</div>
    <div class="panel-body">

    {!! Form::model($user, ['route' => ['user.update', $user->id], 'method' => 'PATCH']) !!}

        @include('user-mgmt._user', ['roles' => $roles, 'submitLabel' => 'Update'])

    {!! Form::close() !!}

    
    </div>
</div>

@stop

resources/views/user-mgmt/index.blade.php
@extends('barang.base')
@section('action-content')
    <!-- Main content -->
<section class="content">
      <div class="box">
  <div class="box-header">
    <div class="row">
        <div class="col-sm-10">
          <h3 class="box-title">List  User</h3><br><br><br>
          <a href="{{ action('UserController@create') }}" class="btn btn-success btn-sm mb-2">
            <i class="fa fa-plus-circle"></i> Tambah User Baru
        </a>
        </div>
        <div>
        
        </div>
    </div>
  </div>
  <!-- /.box-header -->
  <div class="box-body">
      <div class="row">
        <div class="col-sm-6"></div>
        <div class="col-sm-6"></div>
      </div>
     
    <div id="example2_wrapper" class="table table-bordered table-striped">
      <div class="row">
        <div class="col-sm-12 col-xs-5 ">
        <table id="userDtab" class="table table-xs table-striped table-bordered" style="width:100%">
            <thead>
                <tr>
                <th>Action</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Role</th>
                </tr>
            </thead>
            <tbody>
                    @forelse ($users as $user)
                    <tr>
                        <td class="align-middle">
                            <span>
                                <a href="{{ route('user.edit', ['id' => $user->id]) }}" class="btn btn-outline-primary btn-sm">
                                    <i class="fa fa-edit"></i>
                                </a>
                                <a onclick="return confirm('Are you sure?')" href="{{ route('user.delete', ['id' => $user->id]) }}" class="btn btn-outline-danger btn-sm">
                                    <i class="fa fa-trash"></i>
                                </a>
                            </span>
                        </td>
                        <td>{{ $user->name }}</td>
                        <td>{{ $user->email }}</td>
                        <td>{{ $user->role_name }}</td>
                      
                    </tr>
                    @empty
                    <tr>
                        <td colspan="5" class="text-center text-muted">Tidak ada data</td>
                        <td style="display: none;"></td>
                        <td style="display: none;"></td>
                        <td style="display: none;"></td>
                        <td style="display: none;"></td>
                    </tr>
                @endforelse
            </tbody>
        </table>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-5">
        </div>
        <div class="col-sm-7">
          <div class="dataTables_paginate paging_simple_numbers" id="example2_paginate">
        
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- /.box-body -->
</div>
    </section>
    <!-- /.content -->
  </div>
@endsection

resources/views/user-mgmt/index1.blade.php
@extends('user-mgmt.base')
@section('action-content')
    <!-- Main content -->
    
    <div class="panel panel-default">
    <div class="panel-body">
        <div>
        <!-- <a href="{{ action('UserController@create') }}" class="btn btn-info btn-sm mb-2"> -->
        <a href="{{ route('user.create') }}" class="btn btn-info btn-sm mb-2">
            <i class="fa fa-plus-circle"></i> Tambah User
        </a>
        </div>
        <br><br>
        <table id="userDtab" class="table table-xs table-striped table-bordered" style="width:100%">
            <thead>
                <tr>
                    <th>Action</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Role</th>
                </tr>
            </thead>
            <tbody>
                @forelse ($users as $user)
                    <tr>
                        <td class="align-middle">
                            <span>
                                <a href="{{ route('user.edit', ['id' => $user->id]) }}" class="btn btn-outline-primary btn-sm">
                                    <i class="fa fa-edit"></i>
                                </a>
                                <a onclick="return confirm('Are you sure?')" href="{{ route('user.delete', ['id' => $user->id]) }}" class="btn btn-outline-danger btn-sm">
                                    <i class="fa fa-trash"></i>
                                </a>
                            </span>
                        </td>
                        <td>{{ $user->name }}</td>
                        <td>{{ $user->email }}</td>
                        <td>{{ $user->role_name }}</td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="5" class="text-center text-muted">Tidak ada data</td>
                        <td style="display: none;"></td>
                        <td style="display: none;"></td>
                        <td style="display: none;"></td>
                        <td style="display: none;"></td>
                    </tr>
                @endforelse
            </tbody>
        </table>

    </div>
</div>

<script>
</script>

@endsection