routes/web.php
<?php

Auth::routes();

Route::group(['middleware' =>['auth']],function(){
    Route::get('/', 'DashboardController@index')->name('dashboard');
    Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');
    
    Route::group(['middleware' => ['gudang']], function() {
        Route::get('penerimaan', 'PembelianController@penerimaan')->name('penerimaan.index');
        Route::get('penerimaan/{pembelian}', 'PembelianController@show')->name('penerimaan.show');
        Route::get('penerimaan/{pembelian}/terima', 'PembelianController@terima')->name('penerimaan.terima');
    });

    Route::group(['middleware' => ['admin']], function() {
        // User
        Route::resource('user', 'UserController');
        // Barang
        Route::get('barang/{barang}/delete', 'BarangController@destroy')->name('barang.delete');
        Route::resource('barang', 'BarangController');
        // Supplier
        Route::get('supplier/{supplier}/delete', 'SupplierController@destroy')->name('supplier.delete');
        Route::resource('supplier', 'SupplierController');
        // Pembelian Barang
        Route::get('pembelian/tambah-barang', 'PembelianController@tambahBarang')->name('pembelian.tambah-barang');
        Route::get('pembelian/{pembelian}/delete', 'PembelianController@destroy')->name('pembelian.delete');
        Route::resource('pembelian', 'PembelianController');
    });

    Route::group(['middleware' => ['kasir']], function() {
        Route::resource('stock-barang', 'StockBarangController');
        Route::get('penjualan-barang/tambah-barang', 'PenjualanBarangController@tambahBarang')->name('penjualan-barang.tambah-barang');
        Route::resource('penjualan-barang', 'PenjualanBarangController');
    });
});

resources/views/layouts/app-base.blade.php
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>IM| Inventory Management</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.6 -->
    <link href="{{ asset('bootstrap/css/bootstrap.min.css') }}" rel="stylesheet" type="text/css">
    <!-- Font Awesome -->
    <link href="{{ asset('font-awesome/css/font-awesome.min.css') }}" rel="stylesheet">
    <!-- Morris chart -->
    <link rel="stylesheet" href="{{ asset('plugins/morris/morris.css') }}">
    <!-- DataTables CSS -->
    <link href="{{ asset('datatables-plugins/dataTables.bootstrap.css') }}" rel="stylesheet">
    <!-- DataTables Responsive CSS -->
    <link href="{{ asset('datatables-responsive/dataTables.responsive.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('datatables/FixedHeader-3.1.4/css/fixedHeader.dataTables.min.css') }}">    
    <!-- Select2js -->
    <link href="{{ asset('css/select2.min.css') }}" rel="stylesheet">
    <!-- Ionicons -->
    <link rel="stylesheet" href="{{ asset('bootstrap/css/ionicons.min.css') }}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{ asset('dist/css/AdminLTE.min.css') }}">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="{{ asset('dist/css/skins/_all-skins.min.css') }}">
    <!-- iCheck -->
    <link rel="stylesheet" href="{{ asset('plugins/iCheck/flat/blue.css') }}">
    <!-- jvectormap -->
    <link rel="stylesheet" href="{{ asset('plugins/jvectormap/jquery-jvectormap-1.2.2.css') }}">
    <!-- Date Picker -->
    <link rel="stylesheet" href="{{ asset('plugins/datepicker/datepicker3.css') }}">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="{{ asset('plugins/daterangepicker/daterangepicker.css') }}">
    <!-- bootstrap wysihtml5 - text editor -->
    <link rel="stylesheet" href="{{ asset('plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css') }}">
    <!-- jQuery 2.2.3 -->
    <script src="{{ asset('jquery/jquery.min.js') }}"></script>
    <script src="{{ asset('bootstrap/css/jquery-ui.min.js') }}"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <!-- <script> $.widget.bridge('uibutton', $.ui.button);</script> -->
    <!-- Bootstrap 3.3.6 -->
    <script src="{{ asset('bootstrap/js/bootstrap.min.js') }}"></script>
    <!-- Datatables -->
    <script src="{{ asset('datatables/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('datatables-plugins/dataTables.bootstrap.min.js') }}"></script>
    <script src="{{ asset('datatables-responsive/dataTables.responsive.js') }}"></script>
    <script src="{{ asset('datatables/FixedHeader-3.1.4/js/dataTables.fixedHeader.min.js') }}"></script>
    <!-- Select2js -->
    <script src="{{ asset('js/select2.min.js') }}"></script>
    <!-- Morris.js charts -->
    <script src="{{ asset('bootstrap/js/raphael-min.js') }}"></script>
    <script src="{{ asset('plugins/morris/morris.min.js') }}"></script>
    <!-- Sparkline -->
    <script src="{{ asset('plugins/sparkline/jquery.sparkline.min.js') }}"></script>
    <!-- jvectormap -->
    <script src="{{ asset('plugins/jvectormap/jquery-jvectormap-1.2.2.min.js') }}"></script>
    <script src="{{ asset('plugins/jvectormap/jquery-jvectormap-world-mill-en.js') }}"></script>
    <!-- jQuery Knob Chart -->
    <script src="{{ asset('plugins/knob/jquery.knob.js') }}"></script>
    <!-- daterangepicker -->
    <script src="{{ asset('bootstrap/js/moment.min.js') }}"></script>
    <script src="{{ asset('plugins/daterangepicker/daterangepicker.js') }}"></script>
    <!-- datepicker -->
    <script src="{{ asset('plugins/datepicker/bootstrap-datepicker.js') }}"></script>
    <!-- Bootstrap WYSIHTML5 -->
    <script src="{{ asset('plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js') }}"></script>
    <!-- Slimscroll -->
    <script src="{{ asset('plugins/slimScroll/jquery.slimscroll.min.js') }}"></script>
    <!-- FastClick -->
    <script src="{{ asset('plugins/fastclick/fastclick.js') }}"></script>
    <!-- AdminLTE App -->
    <script src="{{ asset('dist/js/app.min.js') }}"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <!-- <script src="dist/js/pages/dashboard.js"></script> -->
    <!-- AdminLTE for demo purposes -->
    <script src="{{ asset('dist/js/demo.js') }}"></script>

    @yield('libs')
</head>

<body class="hold-transition skin-blue sidebar-mini">
    <div id="wrapper">
        <!-- Main Header -->
        @include('layouts.header')
        <!-- Sidebar -->
        @include('layouts.sidebar')
        <!-- Left side column. contains the logo and sidebar -->

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <section class="content-header">
                <h1>@yield('content-header')</h1>
            </section>
            <section class="content">
                @include('layouts.flash-notification')
                @yield('content')
            </section>
        </div>
    </div>

    <script>
        $('#flash-overlay-modal').modal();
        $('div.alert').not('.alert-important').delay(3000).slideUp(350);

        $(document).ready(function () {
            if ($('.select').length > 0) {
                $('.select').select2({
                    selectOnClose: true,
                    width: '100%'
                });
            }
        });

    </script>

</body>

</html>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('public/css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @if (Auth::guest())
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endif
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('public/js/app.js') }}"></script>
</body>
</html>

resources/views/layouts/flash-notification.blade.php
@if (Session::has('flash_notification_message'))

    <div class="alert
                alert-{{ Session::has('flash_notification_level') ? session('flash_notification_level') : 'success' }}
                {{ Session::has('flash_notification_important') ? 'alert-important' : '' }}"
                role="alert"
    >
        @if (Session::has('flash_notification_important'))
            <button type="button"
                    class="close"
                    data-dismiss="alert"
                    aria-hidden="true"
            >&times;</button>
        @endif

        {{ session('flash_notification_message') }}
    </div>

@endIf

resources/views/layouts/footer.blade.php
<footer class="main-footer">
    <div class="pull-right hidden-xs">
      <b>Version</b> 2.3.8
    </div>
    <strong>Copyright &copy; 2019 <a href=""></a>.</strong> All rights
    reserved.
  </footer>

resources/views/layouts/header.blade.php
<header class="main-header">
    <!-- Logo -->
    <a href="" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>A</b>LT</span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b></b>ER@TEL PRIMA</span>
      {{-- <span class="logo-lg"><b></b></span> --}}
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
        <span class="sr-only"></span>
      </a>

      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <!-- Messages: style can be found in dropdown.less-->
          <li class="dropdown messages-menu">
          </li>
          <!-- Notifications: style can be found in dropdown.less -->
          <li class="dropdown notifications-menu">
            
          
          </li>
         
          <!-- User Account: style can be found in dropdown.less -->
          <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            {{ auth()->user()->name }}<i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
              <!-- <span class="hidden-xs">Alexander Pierce</span> -->
            </a>
            <ul class="dropdown-menu">
              <!-- User image -->
              <li class="user-header">
                <img src="dist/img/LOGO EP.jpg" class="img-circle" alt="User Image">
                <!-- <li><a href="#" onclick="event.preventDefault();$('#logout-form').submit();"><i class="fa fa-sign-out fa-fw"></i> Logout</a></li> -->

                <p>
                  Hello {{ Auth::user()->name}}
                </p>
              </li>
              <!-- Menu Body -->
              <li class="user-body">
                <!-- /.row -->
              </li>
              <!-- Menu Footer-->
              <li class="user-footer">
              @if (Auth::guest())
                <div class="pull-left">
                  <a href="{{ route('login')}}" class="btn btn-default btn-flat">Login</a>
                </div>
                @else
                <div class="pull-left">
                    <!-- <a href="{{ url('profile') }}" class="btn btn-default btn-flat">Profile</a> -->
                </div>
                <div class="pull-right">
                  <a class="btn btn-default btn-flat" href="{{ route('logout') }}" onclick="event.preventDefault();document.getElementById('logout-form').submit();">
                  Logout</a>
                 
                </div>
                @endif
              </li>
            </ul>
          </li>
          <!-- Control Sidebar Toggle Button -->
          <li>
            <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
          </li>
        </ul>
      </div>
    </nav>
  </header>
  <form id="logout-form" action="{{ route('logout')}}" method="POST" style="display: none;">
  {{ csrf_Field()}}
  </form>

resources/views/layouts/navbar.blade.php
<!-- Navigation -->
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0;background:#337ab7;">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{{ route('dashboard') }}" style="color:#fff">Inventory Sytem Eratel Prima</a>
    </div>
    <!-- /.navbar-header -->

    <ul class="nav navbar-top-links navbar-right">
        <!-- /.dropdown -->
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#" style="color:#fff">
                {{ auth()->user()->name }}<i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
            </a>
            <ul class="dropdown-menu dropdown-user">
                <li><a href="#" onclick="event.preventDefault();$('#logout-form').submit();"><i class="fa fa-sign-out fa-fw"></i> Logout</a></li>
            </ul>
            <form id="logout-form" action="{{ route('logout') }}" method="post" style="display:none;">{{ csrf_field() }}</form>
            <!-- /.dropdown-user -->
        </li>
        <!-- /.dropdown -->
    </ul>
    <!-- /.navbar-top-links -->

    <div class="navbar-default sidebar" role="navigation">
        <div class="sidebar-nav navbar-collapse">
            <ul class="nav" id="side-menu">
                <li>
                    <a href="{{ route('dashboard') }}"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                </li>
                <li>
                </li>
                @if (auth()->user()->role_id == 1 || auth()->user()->role_id == 3)
                <li>
                    <a href="#"><i class="fa fa-calendar fa-fw"></i> Event Management<span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li>
                       
                        </li>
                        <li>
                        </li>
                    </ul>
                    <!-- /.nav-second-level -->
                </li>
                @if (auth()->user()->role_id == 1)
                <li>
                </li>
                @endIf
                @endIf
            </ul>
        </div>
        <!-- /.sidebar-collapse -->
    </div>
    <!-- /.navbar-static-side -->
</nav>

resources/views/layouts/search.blade.php
<div class="box box-default">
  <div class="box-header with-border">
    <h3 class="box-title">{{isset($title) ? $title : 'Search'}}</h3>

    <div class="box-tools pull-right">
      <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
    </div>
  </div>
  <!-- /.box-header -->
  <div class="box-body">
    {{ $slot }}
  </div>
  <!-- /.box-body -->
  <div class="box-footer">
    <button type="submit" class="btn btn-primary">
      <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
      search
    </button>
  </div>
</div>

resources/views/layouts/sidebar.blade.php
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="{{ asset('dist/img/LOGO EP.jpg') }}" alt="User Image" class="img-cirlce">
            </div>
        </div>
        <!-- search form -->
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search...">
                <span class="input-group-btn">
                    <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i
                            class="fa fa-search"></i>
                    </button>
                </span>
            </div>
        </form>
        <!-- /.search form -->
        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu">
            <li class="header"></li>
            <li class="active treeview">
                <a href="#">
                    <i class="fa fa-dashboard"></i> <span>Dashboard</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                </ul>
            </li>
            {{-- admin --}}
            @if (auth()->user()->role->name == "administrator")
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-pie-chart"></i>
                    <span>CHARTS</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href=""><i class="fa fa-circle-o text-red"></i>Profit</a></li>
                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-laptop"></i>
                    <span>ADMIN</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="{{ route('barang.index') }}"><i class="fa fa-circle-o text-aqua"></i>Master Barang</a>
                    </li>
                    <li><a href="{{ route('supplier.index') }}"><i class="fa fa-circle-o text-red"></i>Master
                            Supplier</a></li>
                    <li><a href="{{ route('pembelian.index') }}"><i class="fa fa-circle-o text-green"></i>Pembelian
                            Barang / PO</a></li>
                </ul>
            </li>
            @endif
            {{--  --}}
            @if (auth()->user()->role->name == "gudang" )
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-laptop"></i>
                    <span>GUDANG</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="{{ route('penerimaan.index') }}"><i class="fa fa-circle-o text-green"></i>Penerimaan Barang</a></li>
                </ul>
            </li>
            @endif
            @if (auth()->user()->role->name == "kasir")
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-edit"></i> <span>KASIR</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="{{ route('stock-barang.index') }}"><i class="fa fa-circle-o text-red"></i>Stok
                            Barang</a></li>
                    <li><a href="{{ route('penjualan-barang.index') }}"><i
                                class="fa fa-circle-o text-green"></i>Penjualan Barang</a></li>
                </ul>
            </li>
            @endif
            @if (auth()->user()->role->name != "gudang")
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-table"></i> <span>LAPORAN</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href=""><i class="fa fa-circle-o text-yellow"></i>Laporan Penjualan</a></li>
                    @if (auth()->user()->role->name == "administrator" || auth()->user()->role->name == "manager")
                        <li><a href=""><i class="fa fa-circle-o text-white"></i>Laporan Pembelian</a></li>
                        <li><a href=""><i class="fa fa-circle-o text-blue"></i>Laporan Profit</a></li>
                    @endif
                </ul>
            </li>
            @endif
            @if (auth()->user()->role->name == "administrator")    
            <li>
                <a href="{{ route('user.index') }}"><i class="fa fa-users fa-fw"></i><span> User Management</span></a>
            </li>
            @endif
        </ul>
    </section>
    <!-- /.sidebar -->
</aside>

resources/views/layouts/top-navbar.blade.php
<nav class="navbar navbar-expand-sm bg-primary navbar-dark fixed-top shadow">
  <a class="navbar-brand" href="#">In-Ven</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="collapsibleNavbar">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{{ route('welcome') }}">Home</a>
      </li>
      <li class="nav-item">
        <!-- <a class="nav-link" href="{{ route('attendance.index') }}">Workshop Attendance</a> -->
      </li>
      @if (Auth::user()->role_id == 1)
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
          Master
        </a>
        <div class="dropdown-menu">
          <!-- <a class="dropdown-item" href="{{ route('event.index') }}">Event</a> -->
          <!-- <a class="dropdown-item" href="{{ route('participant.index') }}">Participant</a> -->
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ route('user.index') }}">Admin</a>
      </li>
      @endIf
    </ul>
    <ul class="navbar-nav">
      <li class="nav-item">
        <a href="#" class="nav-link" onclick="event.preventDefault();$('#logout-form').submit();">Logout</a>
        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
            {{ csrf_field() }}
        </form>
      </li>
    </ul>
  </div>
</nav>

resources/views/layouts/two-cols-date-search-row.blade.php
<div class="row">
  @php
    $index = 0;
  @endphp
  @foreach ($items as $item)
    <div class="col-md-6">
      <div class="form-group">
          @php
            $stringFormat =  strtolower(str_replace(' ', '', $item));
          @endphp
        <label class="col-md-3 control-label">{{$item}}</label>
        <div class="col-md-7">
            <div class="input-group date">
                <div class="input-group-addon">
                    <i class="fa fa-calendar"></i>
                </div>
                <input type="text" value="{{isset($oldVals) ? $oldVals[$index] : ''}}" name="<?=$stringFormat?>" class="form-control pull-right" id="<?=$stringFormat?>" placeholder="{{$item}}" required>
            </div>
        </div>
      </div>
    </div>
  @php
    $index++;
  @endphp
  @endforeach
</div>

resources/views/layouts/two-cols-search-row.blade.php
<div class="row">
  @php
    $index = 0;
  @endphp
  @foreach ($items as $item)
    <div class="col-md-6">
      <div class="form-group">
          @php
            $stringFormat =  strtolower(str_replace(' ', '', $item));
          @endphp
          <label for="input<?=$stringFormat?>" class="col-sm-3 control-label">{{$item}}</label>
          <div class="col-sm-9">
            <input value="{{isset($oldVals) ? $oldVals[$index] : ''}}" type="text" class="form-control" name="<?=$stringFormat?>" id="input<?=$stringFormat?>" placeholder="{{$item}}">
          </div>
      </div>
    </div>
  @php
    $index++;
  @endphp
  @endforeach
</div>